matrix:
  include:
    - language: cpp
      os:
        - linux
        - osx
      compiler:
        - gcc
        - clang
      addons:
        apt:
          packages:
            - cppcheck
            - cmake
            - gcc-4.9
      before_install:
        - sudo pip install cpplint
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install build-essential; fi
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install valgrind; fi
        - git clone https://github.com/dacap/clip.git ./vendor/clip
      script:
        # build doShell
        - cmake CMakeLists.txt && make

        # lint c++ source w/ cppcheck
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cppcheck --enable=all --force --language=c++ -U_MSC_VER -U__PGI -U__SUNPRO_CC -U_MSC_VER_MSC_VER -U__GNUC__ -U__IBMCPP__ ./doShell/*; fi

        # lint c++ source for google styleguide breaches
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cpplint --recursive --recursive --extensions=cc,h doShell; fi
      after_success:
        # ensure doShell can run
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./bin/linux/dosh ; fi
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./bin/mac/dosh ; fi
